---
title: Talk template
output:
  xaringan::moon_reader:
  #  self_contained: TRUE
    includes:
      in_header: conf/style-header.html
    lib_dir: assets
    seal: false
    css: ["default", "conf/css/style.css", "conf/css/fonts.css"]
    nature:
      beforeInit: ["conf/js/gifffer.min.js", "conf/js/style-macros.js"]
---

```{r setup, echo = F}
knitr::opts_chunk$set(
  comment = "#",
  #cache = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 5.25,
  fig.align = 'center',
  fig.retina = 3
)

# base plot layout
mypar = list(mar = c(3,3,0.5,0.5), mgp = c(1.5, 0.3, 0), tck = -.008)

# xaringan Extra
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = TRUE  #<<
)
xaringanExtra::use_editable(expires = 1)
xaringanExtra::use_panelset()
```
class: middle, title-slide

<div class="my-logo-left"></div>

# Living Planet Index
<hr width="65%" align="left" size="0.3" color="orange"></hr>

### Katherine Hébert & Vincent Bellavance

<br><br><br><br><br>
<i class="fa fa-twitter fa-lg" style="color:#e7e8e2"></i> [@hebert_kat](https://twitter.com/hebert_kat)

<i class="fa fa-twitter fa-lg" style="color:#e7e8e2"></i> [@v_bellavance](https://twitter.com/v_bellavance)
---

# Introduction à l'Indice Planète Vivante

- Qu'est-ce que c'est?

- Qui l'utilise, et pour quoi?

- Ça fonctionne comment?

- Critiques

---
class: middle, center, inverse

# L'Indice Planète Vivante
## Qu'est-ce que c'est?
<hr width="100%" align="left" size="0.3" color="orange"></hr>

---

# Qu'est-ce que c'est?

* Indice global de changement de biodiversité au niveau des populations
<br>
<br>
--

* Inclut maintenant **~21,000 populations** de **~4800 espèces** de mammifères, oiseaux, poissons, reptiles, et amphibiens, grâce aux chercheurs qui soumettent leurs données partout autour du monde!
<br>
<br>
--

* Moyenne aggregée des changements dans l'abondance des populations vertébrés depuis 1970 

---
class: middle, center, inverse

# L'Indice Planète Vivante
## Qui l'utilise, et pour quoi?
<hr width="100%" align="left" size="0.3" color="orange"></hr>

---
class: middle, center, inverse

# L'Indice Planète Vivante
## Ça fonctionne comment?
<hr width="100%" align="left" size="0.3" color="orange"></hr>

---
class: middle, center, inverse

# L'Indice Planète Vivante
## Critiques
<hr width="100%" align="left" size="0.3" color="orange"></hr>

---
